### PR TITLE
Fix/673 remove copy to clipboard for etherscan links

### LINKED ISSUE #673: Copy to clipboard being applied to etherscan link inappropriately
This link to etherscan link gets a copy to clipboard on hover, it shouldn't. 

Or maybe it should be the thing that should end up on your clipboard is the transaction rather than the text "Copy to clipboard"

This from the pending transaction state when associating tokens on /staking/associate
Screenshot 2021-10-20 at 11 37 12

### PR DESCRIPTION
**Pull request by mattrussell36**
Makes the Etherscan link not use the copy popover by default so that for transactions you just get a plain link linking directly to Etherscan. Places where we show Ethereum addresses _do_ get the popover with a link to copy.

- Makes etherscan link not use the popover to copy by default
- Adds copy popovers to places that require it

Closes #673

### CODE REVIEW

**Review by dexturr — APPROVED** [review]

File: src/components/etherscan-link/etherscan-link.tsx [hunk 1]
```diff
@@ -91,21 +91,18 @@ export const EtherscanLink = ({
     );
   };
```
Comment (pgriscti) [inline src/components/etherscan-link/etherscan-link.tsx:93]: Why was this removed? The links are not mono any more.

Comment (mattrussell36) [reply src/components/etherscan-link/etherscan-link.tsx:93]: I dont think this component should define what type of font to use so I'm going to allow you to specify a classname if needed
