### PR TITLE
Fix/960-correct-vote-stats

### LINKED ISSUE #960: Open proposal summary: using all the votes for and against
bring back the vote summary and use the details on each pending vote to build up the total for/ against. These are not yet provided in API for open proposals.

### PR DESCRIPTION
**Pull request by pgriscti**
closes #960

### CODE REVIEW

File: src/routes/governance/hooks.ts [hunk 1]
```diff
@@ -78,17 +81,36 @@ export const useVoteInformation = ({
...
-    [proposal.votes.no.totalTokens]
-  );
+
+  const noTokens = React.useMemo(() => {
+    if (!proposal.votes.no.votes) {
+      return 0;
+    }
+    const totalNoVotes = proposal.votes.no.votes.reduce(
+      (prevValue: number, newValue: Proposal_proposal_votes_no_votes) => {
+        return prevValue + Number(newValue.party.stake.currentStakeAvailable);
```
Comment (mattrussell36) [inline src/routes/governance/hooks.ts:91]: Should be using bignumber here.

File: src/routes/governance/hooks.ts [hunk 2]
```diff
@@ -78,17 +81,36 @@ export const useVoteInformation = ({
...
+    return Number(addDecimal(new BigNumber(totalNoVotes), 18));
+  }, [proposal.votes.no.votes]);
+
+  const yesTokens = React.useMemo(() => {
+    if (!proposal.votes.yes.votes) {
+      return 0;
+    }
+    const totalYesVotes = proposal.votes.yes.votes.reduce(
+      (prevValue: number, newValue: Proposal_proposal_votes_yes_votes) => {
+        return prevValue + Number(newValue.party.stake.currentStakeAvailable);
```
Comment (mattrussell36) [inline src/routes/governance/hooks.ts:104]: Use bignumber

File: src/routes/governance/vote-details.scss [hunk 3]
```diff
@@ -0,0 +1,88 @@
+@import "../../styles/colors";
+
+.proposal-toast {
```
Comment (mattrussell36) [inline src/routes/governance/vote-details.scss:3]: Why have we got a proposal-toast class? We don't have any toasts in this project

File: src/lib/format-locale-number.ts [hunk 4]
```diff
@@ -0,0 +1,11 @@
+import { BigNumber } from "./bignumber";
+
+export const formatLocaleFixedNumber = (value: BigNumber, decimals?: number) => {
```
Comment (mattrussell36) [inline src/lib/format-locale-number.ts:3]: Why exactly do we need this function in place of just using `formatNumber` in `src/lib/format-number.ts`

File: src/routes/governance/hooks.ts (hunk 2 above)
Comment (mattrussell36) [reply src/routes/governance/hooks.ts:104]: Hm using bignumber here has quite a cascading affect of requiring lots of other changes. Lets do as a follow up

Comment (mattrussell36) [reply src/routes/governance/hooks.ts:104]: https://github.com/vegaprotocol/token-frontend/issues/971

File: src/lib/format-locale-number.ts (hunk 4 above)
Comment (mattrussell36) [reply src/lib/format-locale-number.ts:3]: Will do as https://github.com/vegaprotocol/token-frontend/issues/971

File: src/routes/governance/hooks.ts (hunk 1 above)
Comment (mattrussell36) [reply src/routes/governance/hooks.ts:91]: Will do in https://github.com/vegaprotocol/token-frontend/issues/971

**Review by mattrussell36 — APPROVED** [review]
