### PR TITLE
Fix/1003-proposal-details

### LINKED ISSUE #1003: Proposal details. Change tense for closed proposals.
If the vote closed is in the past

- [x] closes on -> closed on
☝️ on both listing and details page

under the "Votes" heading: Vote status: [e.g. Participation not met]. [days left to vote]
- [x] Change to "Vote closed. Failed due to..." [x days ago] 
- [x] or Vote passed [x days ago]
- [x] and if the status is waitingfornodes "Vote passed [x days ago] subject to further actions"

### PR DESCRIPTION
**Pull request by pgriscti**
** Branched off Master **

closes #1003

### CODE REVIEW

File: src/routes/governance/current-proposal-status.tsx [hunk 1]
```diff
@@ -14,36 +15,87 @@ export const CurrentProposalStatus = ({
...
+        <span className="current-proposal-status__fail">
+          {t("majorityNotMet")}
+        </span>
+        <span>&nbsp;{daysClosedAgo}.</span>
+      </>
     );
   }
 
-  if (proposal.state === ProposalState.Failed) {
-    return <span className="current-proposal-status__fail">{t("failed")}</span>;
```
Comment (mattrussell36) [inline src/routes/governance/current-proposal-status.tsx:41]: I don't think this translation is used anywhere else (also `passed`) and can be removed. Could you verify any translation changes and remove any which are unused

File: src/routes/governance/network-change.tsx [hunk 2]
```diff
@@ -34,11 +35,19 @@ export const NetworkChange = ({ proposal }: NetworkChangeProps) => {
             </td>
           </tr>
           <tr>
-            <th>{t("closesOn")}</th>
+            <th>
+              {compareAsc(now, new Date(terms.closingDatetime)) > 0
```
Comment (mattrussell36) [inline src/routes/governance/network-change.tsx:39]: Nitpick: Could use isPast/isFuture in place of compareAsc. Its a bit more clear

**Review by mattrussell36 — CHANGES_REQUESTED** [review]
Looks good. I'd like the translation file updated though 🕊️

**Comment by campbellssource** [comment]
just spotted this one:
Screenshot 2021-12-06 at 10 09 03
vote status when enacted: "Vote status: Should pass" becomes "Vote status: Success"

File: src/routes/governance/current-proposal-status.tsx (hunk 1 above)
Comment (pgriscti) [reply src/routes/governance/current-proposal-status.tsx:41]: done

File: src/routes/governance/proposals-list.tsx [hunk 3]
```diff
@@ -29,6 +29,7 @@ export const ProposalsList = ({ proposals }: ProposalsListProps) => {
     if (row.terms.change.__typename !== "UpdateNetworkParameter") return null;
 
     const type = row.terms.change.__typename;
+    const now = new Date();
```
Comment (dexturr) [inline src/routes/governance/proposals-list.tsx:32]: This will cause a re-render and re-computation every time the function is called. Can we reduce this by using [this pattern](https://github.com/vegaprotocol/token-frontend/blob/d08bedcf6b1633ec08afa6eb30c87b200ca9581a/src/components/epoch-countdown/epoch-countdown.tsx#L50-L61).

Comment (pgriscti) [reply src/routes/governance/proposals-list.tsx]: thanks Dex, actually implemented a simpler fix suggested by Matt.

**Review by mattrussell36 — APPROVED** [review]
