### PR TITLE
Fix/933-remove-vote-summary

### LINKED ISSUE #933: If we are using vote weight on open proposals we should remove vote summary as the data isn't there.
summary on list page highlighted
Screenshot 2021-11-22 at 13 22 29

summary on vote page
Screenshot 2021-11-22 at 13 23 18

### PR DESCRIPTION
**Pull request by pgriscti**
closes #933

### CODE REVIEW

**Review by dexturr — COMMENTED** [review]
We can show this for proposals that have completed, should we just check if the expiry/enactment date is post now?

File: src/routes/governance/vote-details.tsx [hunk 1]
```diff
@@ -81,60 +61,6 @@ export const VoteDetails = ({ proposal }: VoteDetailsProps) => {
...
-          </span>
-          .&nbsp;
-          {proposal.state === ProposalState.Open ? daysLeft : null}
-        </p>
-        <table className="proposal-toast__table">
-          <thead>
-            <tr>
-              <th>{t("for")}</th>
-              <th>
-                <VoteProgress
```
Comment (mattrussell36) [inline src/routes/governance/vote-details.tsx:99]: Is this component used anywhere else. Can we just delete it, we can always get it from version control

**Review by mattrussell36 — APPROVED** [review]

**Review by dexturr — APPROVED** [review]

**Review by mattrussell36 — APPROVED** [review]
