### PR TITLE
fix/361-consistant-date-format

### LINKED ISSUE #361: Improve date formatting style
we use dates in a number of different formats.
This to rationalise these.

Where there is space we should work towards

dd month yyyy

there may be some cases we need to choose a short format.

### PR DESCRIPTION
**Pull request by pgriscti**
closes #361

### CODE REVIEW

File: src/components/epoch-countdown/epoch-countdown.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ import { useTranslation } from "react-i18next";
 
 import arrow from "../../images/back.png";
 
-export const DATE_FORMAT = "yyyy.MM.dd HH:mm";
+const DATE_FORMAT = "dd MMMM yyyy HH:mm";
```
Comment (dexturr) [inline src/components/epoch-countdown/epoch-countdown.tsx:10]: Can we exportn this as a const from some file rather than redefining it everywhere. I think in console we have something like:
* `DATE_FORMAT`
* `SHORT_DATE_FORMAT`

**Review by dexturr — APPROVED** [review]
