### PR TITLE
Fix/909 poll for withdrawals

### LINKED ISSUE #909: Use polling for withdrawals
Make it work on mainnet

### PR DESCRIPTION
**Pull request by dexturr**
Closes #909

### CODE REVIEW

File: src/hooks/use-create-withdrawal.ts [hunk 1]
```diff
@@ -115,38 +104,37 @@ export function useCreateWithdrawal(pubKey: string): [Status, Submit] {
...
-            stopSub();
+            clearInterval(interval);
           }
-        });
-    }
-
-    if (status === Status.Success || status === Status.Failure) {
-      stopSub();
+        } catch (err) {
+          debugger;
```
Comment (dexturr) [inline src/hooks/use-create-withdrawal.ts:128]:
```suggestion
```

**Review by mattrussell36 — APPROVED** [review]
Nice one
