### PR TITLE
Fix/1295 fixes

### LINKED ISSUE #1295: Release token for mainnet release 0.50.3 (and fix bugs)
There are breaking data node changes between current mainnet and 0.50.3 which requires a sync release of the token site.

### PR DESCRIPTION
**Pull request by mattrussell36**
Closes #1295

### CODE REVIEW

File: src/contexts/contracts/collateral-bridge.ts [hunk 1]
```diff
@@ -0,0 +1,80 @@
+import { addDecimal } from "@vegaprotocol/smart-contracts-sdk";
```
Comment (dexturr) [inline src/contexts/contracts/collateral-bridge.ts:1]: chore (blocking): we need to use the old bridge, this is not going to mainnet as part of this release.
