### PR TITLE
fix/1109-show-user-friendly-error-message

### LINKED ISSUE #1109: Bug: rpc error: code = NotFound desc = NotFound error on https://staging.token.vega.xyz/staking
This only seems to be happening when going to the staking section of tokenfrontend on staging 

1. Connect your eth key and wallet
2. Go to https://staging.token.vega.xyz/staking 

Observer error message on the page . The existence of this  error message causes the page to become quiet long and takes a long time to scroll back down 

This is the query response 
{
    "errors": [
        {
            "message": "rpc error: code = NotFound desc = NotFound error",
            "path": [
                "party",
                "delegations",
                2,
                "node"
            ]
        },
        {
            "message": "rpc error: code = NotFound desc = NotFound error",
            "path": [
                "party",
                "delegations",
                3,
                "node"
            ]
        },
        {
            "message": "rpc error: code = NotFound desc = NotFound error",
            "path": [
                "party",
                "delegations",
                4,
                "node"
            ]
        },
        {
            "message": "rpc error: code = NotFound desc = NotFound error",
            "path": [
                "party",
                "delegations",
                0,
                "node"
            ]
        },

Screenshot 2021-12-29 at 15 50 53
Screenshot 2021-12-29 at 15 48 45

expected :  
1. Not sure what the cause of this error is but should be resolved 
2. If the error persists in future we should have a single error message instead of the repetition of the same

### PR DESCRIPTION
**Pull request by pgriscti**
closes #1109

### CODE REVIEW

File: src/routes/staking/staking-nodes-container.tsx [hunk 1]
```diff
@@ -101,7 +101,13 @@ export const StakingNodesContainer = ({
   if (error) {
     return (
       <Callout intent="error" title={t("Something went wrong")}>
-        <pre>{error.message}</pre>
+        <pre>
+          {error.message.includes(
+            "rpc error: code = NotFound desc = NotFound error"
```
Comment (dexturr) [inline src/routes/staking/staking-nodes-container.tsx:106]: Optional: would prefer this to live in a const with a descriptive name

**Review by dexturr — APPROVED** [review]

**Comment by candida-d** [comment]
What does this error actually mean - is there any more useful information that a user could be given to help with debugging/troubleshooting? (IIRC this error has also popped up on Console)
