### PR TITLE
fix issues with links not working

### LINKED ISSUE #981: Signature and Transaction Links are broken on Withdrawals page
Initiate a withdrawal
Now go to Incomplete Withdrawals and Click on Signature Link. It says it's an invalid URL

https://ropsten.etherscan.io/address/0xc5ddb71bb05e72fe565125d4bdb92d67594fc5c83e2e0c2e656443533f766bb96643a2713730430e84d79f6afb5a114a000e425dedadba4987b7c393569432300129016e412f722015f1a75be15c630233686ac596c91e209ba13440cce70d71fa1b42489d436e0e20cbc27ef7de001936cfe1cca3655583c6cf8db9e966fea9780090ad2c02165aeb6e35cbac1288f2100e08db1a4b536b841ea7d48b4f4d9d82216a7e58fd2d340ff7504bec89ba3891c7d9384aaeedf8f5605aec7949761abf5b0069b35a77346dbf00c5f63c840a563224cc4d36c10d68bedb166a0b4466f9dba70742bae5018002bba77f54d3a8e7a5779a7360f47ab9792e34d555609da71dde01

Screenshot 2021-11-29 at 13 55 07

Complete the withdrawal transaction by Clicking on Finish Withdrawal.
Click on Transaction Link. Its says invalid address 

https://ropsten.etherscan.io/address/0x7d5d%E2%80%A693c2

Screenshot 2021-11-29 at 13 57 02

### PR DESCRIPTION
**Pull request by dexturr**
Closes #981

### CODE REVIEW

File: src/routes/withdrawals/index.tsx [hunk 1]
```diff
@@ -234,15 +234,9 @@ export const Withdrawal = ({
...
-              "Loading..."
-            ) : (
-              <EtherscanLink
-                chainId={chainId}
-                address={erc20Approval.signatures}
-                text={truncateMiddle(erc20Approval.signatures)}
-              />
-            )}
+            {!erc20Approval?.signatures
+              ? "Loading..."
```
Comment (pgriscti) [inline src/routes/withdrawals/index.tsx:238]: Can we add this string to our translations file?

**Review by pgriscti — APPROVED** [review]

**Review by mattrussell36 — APPROVED** [review]
